sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy2.7-5.9.0"
  - "pypy3.5-5.8.0"
  - "pypy3.5-5.9.0"
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
  - python: 3.8
    dist: xenial
    sudo: true
  - python: pypy
    dist: xenial
    sudo: true
  - python: pypy3
    dist: xenial
    sudo: true
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=contentful setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: M7BAQliY6Mw7KT1cUB58+tgRLs440xAEapayAHjPIjHeO5i/k6ljBNitS5yP8i6IDNEKKMjvic2nSbcuWesMCkTCwgj8v35LNUuKKQJwu9qp7wNCdzLVOJ1RDaGmO19BGidjfc//N5uE8cGTpyaTXRL2b/Was9j8qwpvgGBkP4VelbyMB7K08/FTLCusci/1teofQ5tahjcKcbQ57qpme1oYAYOaFWW/Av38t47fEihnYcC+VNvlliOI+Gic/cE+AZQUimSM/asEX+qdDn7Ok8OPPC7F1i+rRzEHTQ/1NEaXYm1yK1qJf9KAO4JS6EczwgGzzcUx7O8IUyNDmvgViUXASF+KJByxbj+oEj/VVupFlfl8xnXYiIE79e/rAmCUwrvOoFGiBwXGIRgm1scOLu6ho3KUB1Zgq9D86hGiAcQ4RCJACZv342hHzM9OjKL3y4SbNM22YjVt3w7SW96VKHAgRldnjYEhy5KearmMC1NH5EnxxKk1bD5+VoLzu6BqIaJFAJICxU2W6fhXhHuu6pacO8P5KbLdPon+b3EzPFUt9uzppqVszI2MhQ2Mtc501onJJvzj/IyrYRyjCApKnQHw0svyb4UBHRwInIUiiIj5vZ9yR7G8WBdemnNP5FrcmRUdniy8O2dcbOebJyY9no0k/w+atWdBniK4vyr2q4w=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
