sudo: false
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy3-2.4.0"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]] && [[ $TRAVIS_PYTHON_VERSION != "3.3" ]] && [[ $TRAVIS_PYTHON_VERSION != "pypy3-2.4.0" ]]; then pip install --upgrade pip setuptools; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then pip install --upgrade "pip<8.0" "setuptools<20.0"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]] || [[ $TRAVIS_PYTHON_VERSION == "pypy3-2.4.0" ]]; then pip install --upgrade "pip<10.0" "setuptools<24.0"; fi
install:
  - pip install "pkginfo<1.3"
  - pip install -r requirements.txt
  - pip install "pycparser<2.19" coveralls
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=contentful setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: M7BAQliY6Mw7KT1cUB58+tgRLs440xAEapayAHjPIjHeO5i/k6ljBNitS5yP8i6IDNEKKMjvic2nSbcuWesMCkTCwgj8v35LNUuKKQJwu9qp7wNCdzLVOJ1RDaGmO19BGidjfc//N5uE8cGTpyaTXRL2b/Was9j8qwpvgGBkP4VelbyMB7K08/FTLCusci/1teofQ5tahjcKcbQ57qpme1oYAYOaFWW/Av38t47fEihnYcC+VNvlliOI+Gic/cE+AZQUimSM/asEX+qdDn7Ok8OPPC7F1i+rRzEHTQ/1NEaXYm1yK1qJf9KAO4JS6EczwgGzzcUx7O8IUyNDmvgViUXASF+KJByxbj+oEj/VVupFlfl8xnXYiIE79e/rAmCUwrvOoFGiBwXGIRgm1scOLu6ho3KUB1Zgq9D86hGiAcQ4RCJACZv342hHzM9OjKL3y4SbNM22YjVt3w7SW96VKHAgRldnjYEhy5KearmMC1NH5EnxxKk1bD5+VoLzu6BqIaJFAJICxU2W6fhXhHuu6pacO8P5KbLdPon+b3EzPFUt9uzppqVszI2MhQ2Mtc501onJJvzj/IyrYRyjCApKnQHw0svyb4UBHRwInIUiiIj5vZ9yR7G8WBdemnNP5FrcmRUdniy8O2dcbOebJyY9no0k/w+atWdBniK4vyr2q4w=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
